### ISSUE TITLE
Custom Cards

### ISSUE THREAD

**Issue by zedja123** [sbl1996/ygo-agent#6]
Any way to use custom cards with this?

**Comment by zedja123** [comment]
Also having a problem when executing it:

python -u eval.py --env-id "YGOPro-v0" --deck ../assets/deck/  --num_episodes 32 --strategy random  --lang chinese --num_envs 16
Traceback (most recent call last):
  File "C:\Users\Miguel\Desktop\YUGIOH IA\ygo-agent\scripts\eval.py", line 104, in <module>
    deck = init_ygopro(args.env_id, args.lang, args.deck, args.code_list_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miguel\Desktop\YUGIOH IA\ygo-agent\scripts\ygoai\utils.py", line 44, in init_ygopro
    from ygoenv.ygopro import init_module
ModuleNotFoundError: No module named 'ygoenv.ygopro'

**Comment by sbl1996** [comment]
> Any way to use custom cards with this?

Yes, custom cards can be used with this project. Here's how it works:

- YGO-Agent is built on YGOPro, so custom cards must first be compatible with YGOPro.
- If a custom card runs successfully in YGOPro, it will function the same as official cards in our project.

As for supporting new cards or decks specifically in YGO-Agent, I'm currently working on documentation to explain this process. I'll be adding this information to the README in the coming days.

**Comment by zedja123** [comment]
Thanks for the fast response and hard work on this! I haven't come to make it work yet but I'm really excited for it. Could you try to solve the error on the second message?

**Comment by sbl1996** [comment]
> Also having a problem when executing it:
> 
> python -u eval.py --env-id "YGOPro-v0" --deck ../assets/deck/ --num_episodes 32 --strategy random --lang chinese --num_envs 16 Traceback (most recent call last): File "C:\Users\Miguel\Desktop\YUGIOH IA\ygo-agent\scripts\eval.py", line 104, in deck = init_ygopro(args.env_id, args.lang, args.deck, args.code_list_file) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Miguel\Desktop\YUGIOH IA\ygo-agent\scripts\ygoai\utils.py", line 44, in init_ygopro from ygoenv.ygopro import init_module ModuleNotFoundError: No module named 'ygoenv.ygopro'

Thank you for reporting this issue. Let me clarify a few points and provide some troubleshooting steps:

- As mentioned in the README, this project has only been tested on Linux (specifically WSL Ubuntu) and may not work on other platforms. For the best experience, I recommend running this project on Ubuntu.
- The error message indicates that the ygoenv package is not properly installed. Here's what you can try:
a. Navigate to the project directory: cd C:\Users\Miguel\Desktop\YUGIOH IA\ygo-agent
b. Install the ygoenv package: pip install -e ygoenv
c. If you encounter any errors during this process, please share them so I can provide further assistance.
- If you continue to face issues on Windows, consider setting up WSL2 (Windows Subsystem for Linux) with Ubuntu 22.04. This would allow you to run the project in its tested environment.

**Comment by zedja123** [comment]
On wsl2 I'm facing a Segmentation Fault error, any thoughts on this?

**Comment by zedja123** [comment]
Also did pip install -e ygoenv on ygo-agent and got this error when executing same command:

Traceback (most recent call last):
  File "C:\Users\Miguel\Desktop\YUGIOH IA\ygo-agent\scripts\eval.py", line 104, in <module>
    deck = init_ygopro(args.env_id, args.lang, args.deck, args.code_list_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miguel\Desktop\YUGIOH IA\ygo-agent\scripts\ygoai\utils.py", line 44, in init_ygopro
    from ygoenv.ygopro import init_module
  File "c:\users\miguel\desktop\yugioh ia\ygo-agent\ygoenv\ygoenv\ygopro\__init__.py", line 3, in <module>
    from .ygopro_ygoenv import (
ModuleNotFoundError: No module named 'ygoenv.ygopro.ygopro_ygoenv'

**Comment by sbl1996** [comment]
> On wsl2 I'm facing a Segmentation Fault error, any thoughts on this?

The segmentation fault error you're experiencing is due to a version mismatch with ygopro-core. I've just pushed a fix to address this. Here are the steps to resolve the issue:
1. First, pull the latest commit from the `stable` branch.
2. Then, follow these steps to rebuild the project:
a. Delete the xmake cache: `rm -rf ~/.xmake`
b. Navigate to the project directory and rebuild: `xmake f -y -c && xmake b -r ygopro_ygoenv`
3. Switch to the correct ygopro-scripts version: `cd ygopro-scripts && git checkout 44eff41f`
4. Navigate to `ygo-agent/scripts` and ensure the `script` directory is linked correctly.
5. Try `python -u eval.py --env-id "YGOPro-v0" --deck ../assets/deck/  --num_episodes 32 --strategy random  --lang chinese --num_envs 16`

If you encounter any further issues or need additional clarification, please don't hesitate to ask.

**Comment by zedja123** [comment]
I'm still getting Segmentation Fault error after rebuilding and redoing building process in another folder

**Comment by sbl1996** [comment]
> I'm still getting Segmentation Fault error after rebuilding and redoing building process in another folder

Make sure you run `python -u eval.py` in the `scripts` directory and the `scripts/script` is a soft link of `ygopro-scripts`, and try again.

**Comment by zedja123** [comment]
Did that but still, same Segmentation Fault error

**Comment by sbl1996** [comment]
> Did that but still, same Segmentation Fault error

If it's convenient, could you please join this Discord channel (https://discord.gg/KHh4WD4B)? It would be easier for us to have a more detailed conversation.

**Comment by zedja123** [comment]
Sure! Joining now.

**Comment by sbl1996** [comment]
The issue arises due to a compatibility conflict between pybind11 v2.11 and numpy v2.0. Solved by upgrading pybind11 to 2.13 or downgrading numpy. ygo-agent uses pybind11 v2.13 as the default now.
